name: ihz_bql
description: Bach mai canteen by Nobisoft

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+201191225

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #State management
  get: ^4.1.4
  flutter_bloc: ^7.3.0

  #Utilities
  package_info: ^2.0.0
  permission_handler: 10.2.0
  intl_utils: ^2.1.0
  equatable: ^2.0.3

  #Store
  flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.5

  #Network
  retrofit: ^2.0.0-beta1
  dio: ^4.0.0
  json_annotation: ^4.0.0

  #Custom UI
  shimmer: ^2.0.0

  #Image, video
  flutter_svg: ^0.23.0+1
  cached_network_image: ^3.0.0
  multi_image_picker2: ^5.0.2
  photo_view: ^0.13.0
  better_player: ^0.0.81

  #Dotted
  dotted_border: ^2.0.0+1
  dotted_decoration: ^2.0.0

  #File picker
  file_picker: ^4.2.4
  connectivity_plus: 2.2.0

  #Html view
  flutter_html: ^2.1.5
  html_editor_enhanced: ^2.4.0+1

  #Path provider
  path_provider: ^2.0.7

  #Dialog, etc
  image_picker:

  #Rating bar
  flutter_rating_bar: ^4.0.0
  #url_launcher
  url_launcher: ^6.0.12

  #Firebase
  #firebase_analytics: ^8.3.2
  firebase_core: ^2.8.0
  firebase_messaging: ^14.2.6
  firebase_messaging_platform_interface: ^4.2.16
  firebase_crashlytics: ^3.0.17
  #firebase_dynamic_links: ^2.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0
  syncfusion_flutter_datepicker: ^19.3.57
  fl_chart: ^0.40.6
  charts_flutter: ^0.12.0
  video_player: ^2.2.10
  custom_navigation_bar: ^0.8.2
  fluro: ^2.0.5
  photo_manager: ^2.6.0
  wechat_assets_picker: ^7.2.0
  infinite_scroll_pagination: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0+1
  flutter_lints: ^1.0.4

# For building_info on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    # Area
    - assets/area/
    # Images
    - assets/images/
    # Vector images
    - assets/vectors/
    - assets/images/ic_eye_close.png
    - assets/images/ic_eye_open.png
    - assets/images/ic_logo.png
    - assets/images/ic_warning.png
    - assets/images/ic_image_placeholder.png
    - assets/images/ic_circle_close.png
    - assets/images/ic_success.png
    - assets/images/bg_home_footer.png
    - assets/images/ic_search_delete.png
    - assets/images/ic_back.png
    - assets/images/ic_search.png
    - assets/images/ic_close.png
    - assets/images/ic_user.png
    - assets/images/ic_success_dialog.png
    - assets/images/chat_bubble.png
    - assets/images/contact-book.png
    - assets/images/ic_learning.png
    - assets/images/ic_settings.png
    - assets/images/ic_image_place_holder.png
    - assets/images/ic_edit_red.png
    - assets/images/ic_attach_camera.png
    - assets/images/ic_attach_image.png
    - assets/images/ic_close_no_bg.png
    - assets/images/ic_error.png
    - assets/images/ic_arrow_right_grey.png
    - assets/images/ic_user_grey.png
    - assets/images/ic_logout.png
    - assets/images/ic_push_up.png
    - assets/images/ic_do_exercise.png
    - assets/images/ic_send.png
    - assets/images/diary.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true